### PR TITLE
Bump docker actions

### PR DESCRIPTION
**Pull request by Pesa**

### CODE REVIEW

**Comment by jdillard** [comment]
Would it be better to enable @dependabot for `github-actions`? https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by Pesa** [comment]
IMHO, yes, but the decision is up to the maintainer(s).

**Comment by jdillard** [comment]
@picnixz you mentioned improving automation of the docker images in https://github.com/sphinx-doc/sphinx/issues/11556#issuecomment-1676334396. This is a different aspect of the images, but seems to be inline with automating version updates in general, do you think @dependabot would be ok here?

**Comment by AA-Turner** [comment]
Could we do monthly with grouped updates? That'd be a good balance for me in terms of avoiding too-frequent PRs.

A

**Comment by jdillard** [comment]
`monthly` is an option for [schedule.interval](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval). And so are [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups), but I haven't used those yet. Guessing this would be the syntax:

**.github/dependabot.yml**:
```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "montly"
    groups:
       # Name for the group, which will be used in PR titles and branch names
       all-github-actions:
          # Define patterns to include based on dependency name
          patterns:
            - "*"       # A wildcard that matches all dependencies in the package
                        # ecosystem. Note: using "*" may open a large pull request
```

**Comment by picnixz** [comment]
@jdillard 

>  @picnixz you mentioned improving automation of the docker images in https://github.com/sphinx-doc/sphinx/issues/11556#issuecomment-1676334396. This is a different aspect of the images, but seems to be inline with automating version updates in general, do you think @dependabot would be ok here?

If it's possible, then I think we could automate the process every release. Like when there is a release, publish the corresponding docker image.

**Comment by Pesa** [comment]
Superseded by #16

**Pull request closed without merging**
